version: "3" 
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_data:/home/jovyan/
  db_pg:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/posgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
volumes:
  pgdata:
